services:
  api:
    build: ./rewards-api
    command: bash -c "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -e production -b 0.0.0.0"
    volumes:
      - ./rewards-api:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      APP_URL: http://ui:4000
    networks:
      - rewards-net
  ui:
    build: ./rewards-ui
    command: pnpm start
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:3000/api/v1
    networks:
      - rewards-net

networks:
  rewards-net:
    driver: bridge
